package com.ifi.lab.LabDAO.model.Idex;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdexCounter generated by hbm2java
 */
@Entity()
@Table(name = "idex_counter"
		, catalog = "lab_demo")
@org.hibernate.annotations.Entity(dynamicUpdate = false)
public class IdexCounter implements java.io.Serializable {

	private Integer idexCounterId;
	private IdexSite idexSite;
	private IdexBoiler idexBoiler;
	private IdexCounter idexCounter;
	private IdexInstallation idexInstallation;
	private IdexEnergySupplier idexEnergySupplier;
	private String name;
	private Integer counterType;
	private Integer isSubModule;
	private String compteurVirtuel;
	private String formuleDeCalcul;
	private String nb;
	private String calculDuNc;
	private Float coefficientDeConversion;
	private Float coefficientEnergetique;
	private Set<IdexBoiler> idexBoilers = new HashSet<IdexBoiler>(0);
	private Set<IdexCounter> idexCounters = new HashSet<IdexCounter>(0);
	private Set<IdexReleves> idexReleveses = new HashSet<IdexReleves>(0);

	public IdexCounter() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_counter_id", unique = true, nullable = false)
	public Integer getIdexCounterId() {
		return this.idexCounterId;
	}

	public void setIdexCounterId(Integer idexCounterId) {
		this.idexCounterId = idexCounterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_site_id")
	public IdexSite getIdexSite() {
		return this.idexSite;
	}

	public void setIdexSite(IdexSite idexSite) {
		this.idexSite = idexSite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_boiler_id")
	public IdexBoiler getIdexBoiler() {
		return this.idexBoiler;
	}

	public void setIdexBoiler(IdexBoiler idexBoiler) {
		this.idexBoiler = idexBoiler;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "counter_parent_id")
	public IdexCounter getIdexCounter() {
		return this.idexCounter;
	}

	public void setIdexCounter(IdexCounter idexCounter) {
		this.idexCounter = idexCounter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_installation_id")
	public IdexInstallation getIdexInstallation() {
		return this.idexInstallation;
	}

	public void setIdexInstallation(IdexInstallation idexInstallation) {
		this.idexInstallation = idexInstallation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_energy_supplier_id")
	public IdexEnergySupplier getIdexEnergySupplier() {
		return this.idexEnergySupplier;
	}

	public void setIdexEnergySupplier(IdexEnergySupplier idexEnergySupplier) {
		this.idexEnergySupplier = idexEnergySupplier;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "counter_type")
	public Integer getCounterType() {
		return this.counterType;
	}

	public void setCounterType(Integer counterType) {
		this.counterType = counterType;
	}

	@Column(name = "is_sub_module")
	public Integer getIsSubModule() {
		return this.isSubModule;
	}

	public void setIsSubModule(Integer isSubModule) {
		this.isSubModule = isSubModule;
	}

	@Column(name = "compteur_virtuel", length = 250)
	public String getCompteurVirtuel() {
		return this.compteurVirtuel;
	}

	public void setCompteurVirtuel(String compteurVirtuel) {
		this.compteurVirtuel = compteurVirtuel;
	}

	@Column(name = "formule_de_calcul", length = 250)
	public String getFormuleDeCalcul() {
		return this.formuleDeCalcul;
	}

	public void setFormuleDeCalcul(String formuleDeCalcul) {
		this.formuleDeCalcul = formuleDeCalcul;
	}

	@Column(name = "nb", length = 250)
	public String getNb() {
		return this.nb;
	}

	public void setNb(String nb) {
		this.nb = nb;
	}

	@Column(name = "calcul_du_nc", length = 250)
	public String getCalculDuNc() {
		return this.calculDuNc;
	}

	public void setCalculDuNc(String calculDuNc) {
		this.calculDuNc = calculDuNc;
	}

	@Column(name = "coefficient_de_conversion")
	public Float getCoefficientDeConversion() {
		return this.coefficientDeConversion;
	}

	public void setCoefficientDeConversion(Float coefficientDeConversion) {
		this.coefficientDeConversion = coefficientDeConversion;
	}

	@Column(name = "coefficient_energetique")
	public Float getCoefficientEnergetique() {
		return coefficientEnergetique;
	}

	public void setCoefficientEnergetique(Float coefficientEnergetique) {
		this.coefficientEnergetique = coefficientEnergetique;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexCounter")
	public Set<IdexBoiler> getIdexBoilers() {
		return this.idexBoilers;
	}

	public void setIdexBoilers(Set<IdexBoiler> idexBoilers) {
		this.idexBoilers = idexBoilers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexCounter")
	public Set<IdexCounter> getIdexCounters() {
		return this.idexCounters;
	}

	public void setIdexCounters(Set<IdexCounter> idexCounters) {
		this.idexCounters = idexCounters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexCounter")
	public Set<IdexReleves> getIdexReleveses() {
		return this.idexReleveses;
	}

	public void setIdexReleveses(Set<IdexReleves> idexReleveses) {
		this.idexReleveses = idexReleveses;
	}

}
