package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdexValue generated by hbm2java
 */
@Entity
@Table(name = "idex_value", catalog = "lab_demo")
public class IdexValue implements java.io.Serializable {

	private Integer idexValueId;
	private Integer idexKeyId;
	private String value;
//	private String comment;
	private Integer idexId;
	private Integer objectId;

	public IdexValue() {
	}

	public IdexValue(Integer idexKeyId, String value,
			Integer idexId, Integer objectId) {
		this.idexKeyId = idexKeyId;
		this.value = value;
//		this.comment = comment;
		this.idexId = idexId;
		this.objectId = objectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_value_id", unique = true, nullable = false)
	public Integer getIdexValueId() {
		return this.idexValueId;
	}

	public void setIdexValueId(Integer idexValueId) {
		this.idexValueId = idexValueId;
	}

	@Column(name = "idex_key_id")
	public Integer getIdexKeyId() {
		return this.idexKeyId;
	}

	public void setIdexKeyId(Integer idexKeyId) {
		this.idexKeyId = idexKeyId;
	}

	@Column(name = "value", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

//	@Column(name = "comment", length = 200)
//	public String getComment() {
//		return this.comment;
//	}
//
//	public void setComment(String comment) {
//		this.comment = comment;
//	}

	@Column(name = "idex_id")
	public Integer getIdexId() {
		return this.idexId;
	}

	public void setIdexId(Integer idexId) {
		this.idexId = idexId;
	}

	@Column(name = "object_id")
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

}
