package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexReleves generated by hbm2java
 */
@Entity
@Table(name = "idex_releves", catalog = "lab_demo")
public class IdexReleves implements java.io.Serializable {

	private Integer idexRelevesId;
	private IdexCounter idexCounter;
	private Date month;
	private Float value;

	public IdexReleves() {
	}

	public IdexReleves(IdexCounter idexCounter, Date month, Float value) {
		this.idexCounter = idexCounter;
		this.month = month;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_releves_id", unique = true, nullable = false)
	public Integer getIdexRelevesId() {
		return this.idexRelevesId;
	}

	public void setIdexRelevesId(Integer idexRelevesId) {
		this.idexRelevesId = idexRelevesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_counter_id")
	public IdexCounter getIdexCounter() {
		return this.idexCounter;
	}

	public void setIdexCounter(IdexCounter idexCounter) {
		this.idexCounter = idexCounter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "month", length = 10)
	public Date getMonth() {
		return this.month;
	}

	public void setMonth(Date month) {
		this.month = month;
	}

	@Column(name = "value")
	public Float getValue() {
		return this.value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

}
