package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdexBoiler generated by hbm2java
 */
@Entity
@Table(name = "idex_boiler", catalog = "lab_demo")
public class IdexBoiler implements java.io.Serializable {

	private Integer idexBoilerId;
	private IdexCounter idexCounter;
	private IdexInstallation idexInstallation;
	private String name;
	private String logo;
	private Set<IdexCounter> idexCounters = new HashSet<IdexCounter>(0);

	public IdexBoiler() {
	}

	public IdexBoiler(IdexCounter idexCounter,
			IdexInstallation idexInstallation, String name, String logo,
			Set<IdexCounter> idexCounters) {
		this.idexCounter = idexCounter;
		this.idexInstallation = idexInstallation;
		this.name = name;
		this.logo = logo;
		this.idexCounters = idexCounters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_boiler_id", unique = true, nullable = false)
	public Integer getIdexBoilerId() {
		return this.idexBoilerId;
	}

	public void setIdexBoilerId(Integer idexBoilerId) {
		this.idexBoilerId = idexBoilerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_counter_id")
	public IdexCounter getIdexCounter() {
		return this.idexCounter;
	}

	public void setIdexCounter(IdexCounter idexCounter) {
		this.idexCounter = idexCounter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_installation_id")
	public IdexInstallation getIdexInstallation() {
		return this.idexInstallation;
	}

	public void setIdexInstallation(IdexInstallation idexInstallation) {
		this.idexInstallation = idexInstallation;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "logo", length = 250)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexBoiler")
	public Set<IdexCounter> getIdexCounters() {
		return this.idexCounters;
	}

	public void setIdexCounters(Set<IdexCounter> idexCounters) {
		this.idexCounters = idexCounters;
	}

}
