package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdexEnergySupplier generated by hbm2java
 */
@Entity
@Table(name = "idex_energy_supplier", catalog = "lab_demo")
public class IdexEnergySupplier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idexEnergySupplierId;
	private IdexEnergyType idexEnergyType;
	private IdexInstallation idexInstallation;
	private String name;
//	private String icon;
	private Integer orderBy;
	private String logo;
	private Set<IdexCounter> idexCounters = new HashSet<IdexCounter>(0);

	public IdexEnergySupplier() {
	}

	public IdexEnergySupplier(IdexEnergyType idexEnergyType,
			IdexInstallation idexInstallation, String name, String icon,
			String logo, Set<IdexCounter> idexCounters) {
		this.idexEnergyType = idexEnergyType;
		this.idexInstallation = idexInstallation;
		this.name = name;
		this.idexCounters = idexCounters;
		this.logo = logo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_energy_supplier_id", unique = true, nullable = false)
	public Integer getIdexEnergySupplierId() {
		return this.idexEnergySupplierId;
	}

	public void setIdexEnergySupplierId(Integer idexEnergySupplierId) {
		this.idexEnergySupplierId = idexEnergySupplierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_energy_type_id")
	public IdexEnergyType getIdexEnergyType() {
		return this.idexEnergyType;
	}

	public void setIdexEnergyType(IdexEnergyType idexEnergyType) {
		this.idexEnergyType = idexEnergyType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_installation_id")
	public IdexInstallation getIdexInstallation() {
		return this.idexInstallation;
	}

	public void setIdexInstallation(IdexInstallation idexInstallation) {
		this.idexInstallation = idexInstallation;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "order_by", length = 250)
	public Integer getOrderBy() {
		return orderBy;
	}

	public void setOrderBy(Integer orderBy) {
		this.orderBy = orderBy;
	}

//	@Column(name = "icon", length = 250)
//	public String getIcon() {
//		return this.icon;
//	}
//
//	public void setIcon(String icon) {
//		this.icon = icon;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexEnergySupplier")
	public Set<IdexCounter> getIdexCounters() {
		return this.idexCounters;
	}

	public void setIdexCounters(Set<IdexCounter> idexCounters) {
		this.idexCounters = idexCounters;
	}

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

}
