package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexContratVente generated by hbm2java
 */
@Entity
@Table(name = "idex_contrat_vente", catalog = "lab_demo")
public class IdexContratVente implements java.io.Serializable {

	private Integer idexContratVenteId;
	private String client;
	private String referenceContrat;
	private Date dateDepartIndexation;
	private Date dateDeDebutDeContrat;
	private Date dateDeFinDeContrat;
	private String preavisResiliation;
	private String numeroDeCompteur;

	public IdexContratVente() {
	}

	public IdexContratVente(String client, String referenceContrat,
			Date dateDepartIndexation, Date dateDeDebutDeContrat,
			Date dateDeFinDeContrat, String preavisResiliation,
			String numeroDeCompteur) {
		this.client = client;
		this.referenceContrat = referenceContrat;
		this.dateDepartIndexation = dateDepartIndexation;
		this.dateDeDebutDeContrat = dateDeDebutDeContrat;
		this.dateDeFinDeContrat = dateDeFinDeContrat;
		this.preavisResiliation = preavisResiliation;
		this.numeroDeCompteur = numeroDeCompteur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_contrat_vente_id", unique = true, nullable = false)
	public Integer getIdexContratVenteId() {
		return this.idexContratVenteId;
	}

	public void setIdexContratVenteId(Integer idexContratVenteId) {
		this.idexContratVenteId = idexContratVenteId;
	}

	@Column(name = "client", length = 100)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "reference_contrat", length = 100)
	public String getReferenceContrat() {
		return this.referenceContrat;
	}

	public void setReferenceContrat(String referenceContrat) {
		this.referenceContrat = referenceContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_depart_indexation", length = 10)
	public Date getDateDepartIndexation() {
		return this.dateDepartIndexation;
	}

	public void setDateDepartIndexation(Date dateDepartIndexation) {
		this.dateDepartIndexation = dateDepartIndexation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_debut_de_contrat", length = 10)
	public Date getDateDeDebutDeContrat() {
		return this.dateDeDebutDeContrat;
	}

	public void setDateDeDebutDeContrat(Date dateDeDebutDeContrat) {
		this.dateDeDebutDeContrat = dateDeDebutDeContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_fin_de_contrat", length = 10)
	public Date getDateDeFinDeContrat() {
		return this.dateDeFinDeContrat;
	}

	public void setDateDeFinDeContrat(Date dateDeFinDeContrat) {
		this.dateDeFinDeContrat = dateDeFinDeContrat;
	}

	@Column(name = "preavis_resiliation", length = 100)
	public String getPreavisResiliation() {
		return this.preavisResiliation;
	}

	public void setPreavisResiliation(String preavisResiliation) {
		this.preavisResiliation = preavisResiliation;
	}

	@Column(name = "numero_de_compteur", length = 20)
	public String getNumeroDeCompteur() {
		return this.numeroDeCompteur;
	}

	public void setNumeroDeCompteur(String numeroDeCompteur) {
		this.numeroDeCompteur = numeroDeCompteur;
	}

}
