package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 7, 2016 4:14:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexCostDetail generated by hbm2java
 */
@Entity
@Table(name = "idex_cost_detail"
		, catalog = "lab_demo")
public class IdexCostDetail implements java.io.Serializable {

	private Integer idexCostDetailId;
	private IdexCost idexCost;
	private Float amount;
	private String unit;
	private Date detailDate;
	private Float consumption;
	public IdexCostDetail() {
	}

	public IdexCostDetail(IdexCost idexCost, Float amount, String unit, Date detailDate) {
		this.idexCost = idexCost;
		this.amount = amount;
		this.unit = unit;
		this.detailDate = detailDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_cost_detail_id", unique = true, nullable = false)
	public Integer getIdexCostDetailId() {
		return this.idexCostDetailId;
	}

	public void setIdexCostDetailId(Integer idexCostDetailId) {
		this.idexCostDetailId = idexCostDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_cost_id")
	public IdexCost getIdexCost() {
		return this.idexCost;
	}

	public void setIdexCost(IdexCost idexCost) {
		this.idexCost = idexCost;
	}

	@Column(name = "amount", precision = 12, scale = 0)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Column(name = "unit", length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "detail_date", length = 10)
	public Date getDetailDate() {
		return this.detailDate;
	}

	public void setDetailDate(Date detailDate) {
		this.detailDate = detailDate;
	}

	public Float getConsumption() {
		return consumption;
	}
	@Column(name = "consumption", precision = 12, scale = 0)
	public void setConsumption(Float consumption) {
		this.consumption = consumption;
	}

}
