package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexLivraisonDeBois generated by hbm2java
 */
@Entity
@Table(name = "idex_livraison_de_bois", catalog = "lab_demo")
public class IdexLivraisonDeBois implements java.io.Serializable {

	private Integer idexLivraisonDeBoisId;
	private String noLivraison;
	private Date dateDeLivraison;
	private Float livraisonTonne;
	private Float mwhTotal;
	private Float livraisonM3;
	private Float prixDuM3;
	private Float prixDeLaLivraison;

	public IdexLivraisonDeBois() {
	}

	public IdexLivraisonDeBois(String noLivraison, Date dateDeLivraison,
			Float livraisonTonne, Float mwhTotal, Float livraisonM3,
			Float prixDuM3, Float prixDeLaLivraison) {
		this.noLivraison = noLivraison;
		this.dateDeLivraison = dateDeLivraison;
		this.livraisonTonne = livraisonTonne;
		this.mwhTotal = mwhTotal;
		this.livraisonM3 = livraisonM3;
		this.prixDuM3 = prixDuM3;
		this.prixDeLaLivraison = prixDeLaLivraison;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_livraison_de_bois_id", unique = true, nullable = false)
	public Integer getIdexLivraisonDeBoisId() {
		return this.idexLivraisonDeBoisId;
	}

	public void setIdexLivraisonDeBoisId(Integer idexLivraisonDeBoisId) {
		this.idexLivraisonDeBoisId = idexLivraisonDeBoisId;
	}

	@Column(name = "no_livraison", length = 20)
	public String getNoLivraison() {
		return this.noLivraison;
	}

	public void setNoLivraison(String noLivraison) {
		this.noLivraison = noLivraison;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_livraison", length = 10)
	public Date getDateDeLivraison() {
		return this.dateDeLivraison;
	}

	public void setDateDeLivraison(Date dateDeLivraison) {
		this.dateDeLivraison = dateDeLivraison;
	}

	@Column(name = "livraison_tonne", precision = 12, scale = 0)
	public Float getLivraisonTonne() {
		return this.livraisonTonne;
	}

	public void setLivraisonTonne(Float livraisonTonne) {
		this.livraisonTonne = livraisonTonne;
	}

	@Column(name = "mwh_total", precision = 12, scale = 0)
	public Float getMwhTotal() {
		return this.mwhTotal;
	}

	public void setMwhTotal(Float mwhTotal) {
		this.mwhTotal = mwhTotal;
	}

	@Column(name = "livraison_m3", precision = 12, scale = 0)
	public Float getLivraisonM3() {
		return this.livraisonM3;
	}

	public void setLivraisonM3(Float livraisonM3) {
		this.livraisonM3 = livraisonM3;
	}

	@Column(name = "prix_du_m3", precision = 12, scale = 0)
	public Float getPrixDuM3() {
		return this.prixDuM3;
	}

	public void setPrixDuM3(Float prixDuM3) {
		this.prixDuM3 = prixDuM3;
	}

	@Column(name = "prix_de_la_livraison", precision = 12, scale = 0)
	public Float getPrixDeLaLivraison() {
		return this.prixDeLaLivraison;
	}

	public void setPrixDeLaLivraison(Float prixDeLaLivraison) {
		this.prixDeLaLivraison = prixDeLaLivraison;
	}

}
