package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexBilanEnergetique generated by hbm2java
 */
@Entity
@Table(name = "idex_bilan_energetique", catalog = "lab_demo")
public class IdexBilanEnergetique implements java.io.Serializable {

	private Integer idexBilanEnergetiqueId;
	private Date month;
	private Float gazGeneralM3;
	private Float gazGeneralMwhPci;
	private Float gazCogeCorrigeNm3;
	private Float gazCogeMwhPci;
	private Float mwhBoisMwhPci;
	private Float mwhCogeMwhUtile;
	private Float mwhBoisMwhUtile;
	private Float mwhChaudieresGazMwhUtile;
	private Float totalMwhUtile;
	private Float mwhSstVendus;

	public IdexBilanEnergetique() {
	}

	public IdexBilanEnergetique(Date month, Float gazGeneralM3,
			Float gazGeneralMwhPci, Float gazCogeCorrigeNm3,
			Float gazCogeMwhPci, Float mwhBoisMwhPci, Float mwhCogeMwhUtile,
			Float mwhBoisMwhUtile, Float mwhChaudieresGazMwhUtile,
			Float totalMwhUtile, Float mwhSstVendus) {
		this.month = month;
		this.gazGeneralM3 = gazGeneralM3;
		this.gazGeneralMwhPci = gazGeneralMwhPci;
		this.gazCogeCorrigeNm3 = gazCogeCorrigeNm3;
		this.gazCogeMwhPci = gazCogeMwhPci;
		this.mwhBoisMwhPci = mwhBoisMwhPci;
		this.mwhCogeMwhUtile = mwhCogeMwhUtile;
		this.mwhBoisMwhUtile = mwhBoisMwhUtile;
		this.mwhChaudieresGazMwhUtile = mwhChaudieresGazMwhUtile;
		this.totalMwhUtile = totalMwhUtile;
		this.mwhSstVendus = mwhSstVendus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_bilan_energetique_id", unique = true, nullable = false)
	public Integer getIdexBilanEnergetiqueId() {
		return this.idexBilanEnergetiqueId;
	}

	public void setIdexBilanEnergetiqueId(Integer idexBilanEnergetiqueId) {
		this.idexBilanEnergetiqueId = idexBilanEnergetiqueId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "month", length = 10)
	public Date getMonth() {
		return this.month;
	}

	public void setMonth(Date month) {
		this.month = month;
	}

	@Column(name = "gaz_general_m3", precision = 12, scale = 0)
	public Float getGazGeneralM3() {
		return this.gazGeneralM3;
	}

	public void setGazGeneralM3(Float gazGeneralM3) {
		this.gazGeneralM3 = gazGeneralM3;
	}

	@Column(name = "gaz_general_mwh_pci", precision = 12, scale = 0)
	public Float getGazGeneralMwhPci() {
		return this.gazGeneralMwhPci;
	}

	public void setGazGeneralMwhPci(Float gazGeneralMwhPci) {
		this.gazGeneralMwhPci = gazGeneralMwhPci;
	}

	@Column(name = "gaz_coge_corrige_nm3", precision = 12, scale = 0)
	public Float getGazCogeCorrigeNm3() {
		return this.gazCogeCorrigeNm3;
	}

	public void setGazCogeCorrigeNm3(Float gazCogeCorrigeNm3) {
		this.gazCogeCorrigeNm3 = gazCogeCorrigeNm3;
	}

	@Column(name = "gaz_coge_mwh_pci", precision = 12, scale = 0)
	public Float getGazCogeMwhPci() {
		return this.gazCogeMwhPci;
	}

	public void setGazCogeMwhPci(Float gazCogeMwhPci) {
		this.gazCogeMwhPci = gazCogeMwhPci;
	}

	@Column(name = "mwh_bois_mwh_pci", precision = 12, scale = 0)
	public Float getMwhBoisMwhPci() {
		return this.mwhBoisMwhPci;
	}

	public void setMwhBoisMwhPci(Float mwhBoisMwhPci) {
		this.mwhBoisMwhPci = mwhBoisMwhPci;
	}

	@Column(name = "mwh_coge_mwh_utile", precision = 12, scale = 0)
	public Float getMwhCogeMwhUtile() {
		return this.mwhCogeMwhUtile;
	}

	public void setMwhCogeMwhUtile(Float mwhCogeMwhUtile) {
		this.mwhCogeMwhUtile = mwhCogeMwhUtile;
	}

	@Column(name = "mwh_bois_mwh_utile", precision = 12, scale = 0)
	public Float getMwhBoisMwhUtile() {
		return this.mwhBoisMwhUtile;
	}

	public void setMwhBoisMwhUtile(Float mwhBoisMwhUtile) {
		this.mwhBoisMwhUtile = mwhBoisMwhUtile;
	}

	@Column(name = "mwh_chaudieres_gaz_mwh_utile", precision = 12, scale = 0)
	public Float getMwhChaudieresGazMwhUtile() {
		return this.mwhChaudieresGazMwhUtile;
	}

	public void setMwhChaudieresGazMwhUtile(Float mwhChaudieresGazMwhUtile) {
		this.mwhChaudieresGazMwhUtile = mwhChaudieresGazMwhUtile;
	}

	@Column(name = "total_mwh_utile", precision = 12, scale = 0)
	public Float getTotalMwhUtile() {
		return this.totalMwhUtile;
	}

	public void setTotalMwhUtile(Float totalMwhUtile) {
		this.totalMwhUtile = totalMwhUtile;
	}

	@Column(name = "mwh_sst_vendus", precision = 12, scale = 0)
	public Float getMwhSstVendus() {
		return this.mwhSstVendus;
	}

	public void setMwhSstVendus(Float mwhSstVendus) {
		this.mwhSstVendus = mwhSstVendus;
	}

}
