package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexContratGaz generated by hbm2java
 */
@Entity
@Table(name = "idex_contrat_gaz", catalog = "lab_demo")
public class IdexContratGaz implements java.io.Serializable {

	private Integer idexContratGaz;
	private String fournisseur;
	private String referenceContrat;
	private Date dateDepartIndexation;
	private Date dateDeDebutDeContrat;
	private Date dateDeFinDeContrat;
	private String preavisResiliation;
	private Integer numeroDeCompteur;
	private String indexation;
	private Integer car;
	private Integer cjsSouscrite;
	private Integer partEod;
	private String abonnementDistribution;
	private Integer ntr;
	private Float p0PegMa;
	private Float p0PegEOd;
	private Float stockage;
	private Float ticgn;
	private Float ctss;
	private Float cbiomethane;
	private Float ctaTransport;
	private Float ctaDistribution;
	private Float tvaPartFixe;
	private Float tvaPartVariable;

	public IdexContratGaz() {
	}

	public IdexContratGaz(String fournisseur, String referenceContrat,
			Date dateDepartIndexation, Date dateDeDebutDeContrat,
			Date dateDeFinDeContrat, String preavisResiliation,
			Integer numeroDeCompteur, String indexation, Integer car,
			Integer cjsSouscrite, Integer partEod,
			String abonnementDistribution, Integer ntr, Float p0PegMa,
			Float p0PegEOd, Float stockage, Float ticgn, Float ctss,
			Float cbiomethane, Float ctaTransport, Float ctaDistribution,
			Float tvaPartFixe, Float tvaPartVariable) {
		this.fournisseur = fournisseur;
		this.referenceContrat = referenceContrat;
		this.dateDepartIndexation = dateDepartIndexation;
		this.dateDeDebutDeContrat = dateDeDebutDeContrat;
		this.dateDeFinDeContrat = dateDeFinDeContrat;
		this.preavisResiliation = preavisResiliation;
		this.numeroDeCompteur = numeroDeCompteur;
		this.indexation = indexation;
		this.car = car;
		this.cjsSouscrite = cjsSouscrite;
		this.partEod = partEod;
		this.abonnementDistribution = abonnementDistribution;
		this.ntr = ntr;
		this.p0PegMa = p0PegMa;
		this.p0PegEOd = p0PegEOd;
		this.stockage = stockage;
		this.ticgn = ticgn;
		this.ctss = ctss;
		this.cbiomethane = cbiomethane;
		this.ctaTransport = ctaTransport;
		this.ctaDistribution = ctaDistribution;
		this.tvaPartFixe = tvaPartFixe;
		this.tvaPartVariable = tvaPartVariable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_contrat_gaz", unique = true, nullable = false)
	public Integer getIdexContratGaz() {
		return this.idexContratGaz;
	}

	public void setIdexContratGaz(Integer idexContratGaz) {
		this.idexContratGaz = idexContratGaz;
	}

	@Column(name = "fournisseur", length = 250)
	public String getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(String fournisseur) {
		this.fournisseur = fournisseur;
	}

	@Column(name = "reference_contrat", length = 250)
	public String getReferenceContrat() {
		return this.referenceContrat;
	}

	public void setReferenceContrat(String referenceContrat) {
		this.referenceContrat = referenceContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_depart_indexation", length = 10)
	public Date getDateDepartIndexation() {
		return this.dateDepartIndexation;
	}

	public void setDateDepartIndexation(Date dateDepartIndexation) {
		this.dateDepartIndexation = dateDepartIndexation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_debut_de_contrat", length = 10)
	public Date getDateDeDebutDeContrat() {
		return this.dateDeDebutDeContrat;
	}

	public void setDateDeDebutDeContrat(Date dateDeDebutDeContrat) {
		this.dateDeDebutDeContrat = dateDeDebutDeContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_de_fin_de_contrat", length = 10)
	public Date getDateDeFinDeContrat() {
		return this.dateDeFinDeContrat;
	}

	public void setDateDeFinDeContrat(Date dateDeFinDeContrat) {
		this.dateDeFinDeContrat = dateDeFinDeContrat;
	}

	@Column(name = "preavis_resiliation", length = 250)
	public String getPreavisResiliation() {
		return this.preavisResiliation;
	}

	public void setPreavisResiliation(String preavisResiliation) {
		this.preavisResiliation = preavisResiliation;
	}

	@Column(name = "numero_de_compteur")
	public Integer getNumeroDeCompteur() {
		return this.numeroDeCompteur;
	}

	public void setNumeroDeCompteur(Integer numeroDeCompteur) {
		this.numeroDeCompteur = numeroDeCompteur;
	}

	@Column(name = "indexation", length = 250)
	public String getIndexation() {
		return this.indexation;
	}

	public void setIndexation(String indexation) {
		this.indexation = indexation;
	}

	@Column(name = "car")
	public Integer getCar() {
		return this.car;
	}

	public void setCar(Integer car) {
		this.car = car;
	}

	@Column(name = "cjs_souscrite")
	public Integer getCjsSouscrite() {
		return this.cjsSouscrite;
	}

	public void setCjsSouscrite(Integer cjsSouscrite) {
		this.cjsSouscrite = cjsSouscrite;
	}

	@Column(name = "part_eod")
	public Integer getPartEod() {
		return this.partEod;
	}

	public void setPartEod(Integer partEod) {
		this.partEod = partEod;
	}

	@Column(name = "abonnement_distribution", length = 250)
	public String getAbonnementDistribution() {
		return this.abonnementDistribution;
	}

	public void setAbonnementDistribution(String abonnementDistribution) {
		this.abonnementDistribution = abonnementDistribution;
	}

	@Column(name = "ntr")
	public Integer getNtr() {
		return this.ntr;
	}

	public void setNtr(Integer ntr) {
		this.ntr = ntr;
	}

	@Column(name = "p0_peg_ma", precision = 12, scale = 0)
	public Float getP0PegMa() {
		return this.p0PegMa;
	}

	public void setP0PegMa(Float p0PegMa) {
		this.p0PegMa = p0PegMa;
	}

	@Column(name = "p0_peg_eOd", precision = 12, scale = 0)
	public Float getP0PegEOd() {
		return this.p0PegEOd;
	}

	public void setP0PegEOd(Float p0PegEOd) {
		this.p0PegEOd = p0PegEOd;
	}

	@Column(name = "stockage", precision = 12, scale = 0)
	public Float getStockage() {
		return this.stockage;
	}

	public void setStockage(Float stockage) {
		this.stockage = stockage;
	}

	@Column(name = "ticgn", precision = 12, scale = 0)
	public Float getTicgn() {
		return this.ticgn;
	}

	public void setTicgn(Float ticgn) {
		this.ticgn = ticgn;
	}

	@Column(name = "ctss", precision = 12, scale = 0)
	public Float getCtss() {
		return this.ctss;
	}

	public void setCtss(Float ctss) {
		this.ctss = ctss;
	}

	@Column(name = "cbiomethane", precision = 12, scale = 0)
	public Float getCbiomethane() {
		return this.cbiomethane;
	}

	public void setCbiomethane(Float cbiomethane) {
		this.cbiomethane = cbiomethane;
	}

	@Column(name = "cta_transport", precision = 12, scale = 0)
	public Float getCtaTransport() {
		return this.ctaTransport;
	}

	public void setCtaTransport(Float ctaTransport) {
		this.ctaTransport = ctaTransport;
	}

	@Column(name = "cta_distribution", precision = 12, scale = 0)
	public Float getCtaDistribution() {
		return this.ctaDistribution;
	}

	public void setCtaDistribution(Float ctaDistribution) {
		this.ctaDistribution = ctaDistribution;
	}

	@Column(name = "tva_part_fixe", precision = 12, scale = 0)
	public Float getTvaPartFixe() {
		return this.tvaPartFixe;
	}

	public void setTvaPartFixe(Float tvaPartFixe) {
		this.tvaPartFixe = tvaPartFixe;
	}

	@Column(name = "tva_part_variable", precision = 12, scale = 0)
	public Float getTvaPartVariable() {
		return this.tvaPartVariable;
	}

	public void setTvaPartVariable(Float tvaPartVariable) {
		this.tvaPartVariable = tvaPartVariable;
	}

}
