package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexInstallation generated by hbm2java
 */
@Entity
@Table(name = "idex_installation", catalog = "lab_demo")
public class IdexInstallation implements java.io.Serializable {

	private Integer idexInstallationId;
	private String codeDeLinstallation;
	private String name;
	private Float lng;
	private Float lat;
	private Boolean isUpdateable;
	private String energyReportFile;
	private String costReportFile;
	private Set<IdexBoiler> idexBoilers = new HashSet<IdexBoiler>(0);
	private Set<IdexSite> idexSites = new HashSet<IdexSite>(0);
	private Set<IdexCounter> idexCounters = new HashSet<IdexCounter>(0);
	private Set<IdexEnergySupplier> idexEnergySuppliers = new HashSet<IdexEnergySupplier>(
			0);
	
	@Column(name = "is_consommation_first")
	private Boolean isConsommationFirst;

	public IdexInstallation() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_installation_id", unique = true, nullable = false)
	public Integer getIdexInstallationId() {
		return this.idexInstallationId;
	}

	public void setIdexInstallationId(Integer idexInstallationId) {
		this.idexInstallationId = idexInstallationId;
	}
	
	@Column(name = "energy_report_file", length = 250)
	public String getEnergyReportFile() {
		return energyReportFile;
	}

	public void setEnergyReportFile(String energyReportFile) {
		this.energyReportFile = energyReportFile;
	}

	@Column(name = "cost_report_file", length = 250)
	public String getCostReportFile() {
		return costReportFile;
	}

	public void setCostReportFile(String costReportFile) {
		this.costReportFile = costReportFile;
	}


	@Column(name = "code_de_linstallation", length = 250)
	public String getCodeDeLinstallation() {
		return this.codeDeLinstallation;
	}

	public void setCodeDeLinstallation(String codeDeLinstallation) {
		this.codeDeLinstallation = codeDeLinstallation;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lng", precision = 12, scale = 0)
	public Float getLng() {
		return this.lng;
	}

	public void setLng(Float lng) {
		this.lng = lng;
	}

	@Column(name = "lat", precision = 12, scale = 0)
	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	@Column(name = "is_updateable")
	public Boolean getIsUpdateable() {
		return this.isUpdateable;
	}

	public void setIsUpdateable(Boolean isUpdateable) {
		this.isUpdateable = isUpdateable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexInstallation")
	public Set<IdexBoiler> getIdexBoilers() {
		return this.idexBoilers;
	}

	public void setIdexBoilers(Set<IdexBoiler> idexBoilers) {
		this.idexBoilers = idexBoilers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexInstallation")
	public Set<IdexSite> getIdexSites() {
		return this.idexSites;
	}

	public void setIdexSites(Set<IdexSite> idexSites) {
		this.idexSites = idexSites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexInstallation")
	public Set<IdexCounter> getIdexCounters() {
		return this.idexCounters;
	}

	public void setIdexCounters(Set<IdexCounter> idexCounters) {
		this.idexCounters = idexCounters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idexInstallation")
	public Set<IdexEnergySupplier> getIdexEnergySuppliers() {
		return this.idexEnergySuppliers;
	}

	public void setIdexEnergySuppliers(
			Set<IdexEnergySupplier> idexEnergySuppliers) {
		this.idexEnergySuppliers = idexEnergySuppliers;
	}

	public Boolean getIsConsommationFirst() {
		return isConsommationFirst;
	}

	public void setIsConsommationFirst(Boolean isConsommationFirst) {
		this.isConsommationFirst = isConsommationFirst;
	}
	

}
