package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdexMeteo generated by hbm2java
 */
@Entity
@Table(name = "idex_meteo", catalog = "lab_demo")
public class IdexMeteo implements java.io.Serializable {

	private Integer idexMeteoId;
	private Integer station;
	private Date date;
	private Integer reel;
	private Float estime;
	private Integer idexInstallationId;
	private Integer demo;

	public IdexMeteo() {
	}

	public IdexMeteo(Integer station, Date date, Integer reel, Float estime,
			Integer idexInstallationId, Integer demo) {
		this.station = station;
		this.date = date;
		this.reel = reel;
		this.estime = estime;
		this.idexInstallationId = idexInstallationId;
		this.demo = demo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_meteo_id", unique = true, nullable = false)
	public Integer getIdexMeteoId() {
		return this.idexMeteoId;
	}

	public void setIdexMeteoId(Integer idexMeteoId) {
		this.idexMeteoId = idexMeteoId;
	}

	@Column(name = "station")
	public Integer getStation() {
		return this.station;
	}

	public void setStation(Integer station) {
		this.station = station;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "reel")
	public Integer getReel() {
		return this.reel;
	}

	public void setReel(Integer reel) {
		this.reel = reel;
	}

	@Column(name = "estime", precision = 12, scale = 0)
	public Float getEstime() {
		return this.estime;
	}

	public void setEstime(Float estime) {
		this.estime = estime;
	}

	@Column(name = "idex_installation_id")
	public Integer getIdexInstallationId() {
		return this.idexInstallationId;
	}

	public void setIdexInstallationId(Integer idexInstallationId) {
		this.idexInstallationId = idexInstallationId;
	}

	@Column(name = "demo")
	public Integer getDemo() {
		return this.demo;
	}

	public void setDemo(Integer demo) {
		this.demo = demo;
	}

}
