package com.ifi.lab.LabDAO.model.Idex;

// Generated Oct 5, 2016 7:13:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdexKey generated by hbm2java
 */
@Entity
@Table(name = "idex_key", catalog = "lab_demo")
public class IdexKey implements java.io.Serializable {

	private Integer idexKeyId;
	private String name;
	private Integer type;
	private String comment;
	private Integer isCounter1;
	private Integer isCounter2;
	private Integer isCounter3;
	private Integer orderNumber;
	private Integer key;
	private Boolean isRequried;

	public IdexKey() {
	}

	public IdexKey(String name, Integer type) {
		this.name = name;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idex_key_id", unique = true, nullable = false)
	public Integer getIdexKeyId() {
		return this.idexKeyId;
	}

	public void setIdexKeyId(Integer idexKeyId) {
		this.idexKeyId = idexKeyId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "comment", length = 100)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "is_counter_1")
	public Integer getIsCounter1() {
		return isCounter1;
	}

	public void setIsCounter1(Integer isCounter1) {
		this.isCounter1 = isCounter1;
	}

	@Column(name = "is_counter_2")
	public Integer getIsCounter2() {
		return isCounter2;
	}

	public void setIsCounter2(Integer isCounter2) {
		this.isCounter2 = isCounter2;
	}

	@Column(name = "is_counter_3")
	public Integer getIsCounter3() {
		return isCounter3;
	}

	public void setIsCounter3(Integer isCounter3) {
		this.isCounter3 = isCounter3;
	}

	@Column(name = "order_number")
	public Integer getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "key")
	public Integer getKey() {
		return key;
	}

	public void setKey(Integer key) {
		this.key = key;
	}

	@Column(name = "is_requried")
	public Boolean getIsRequried() {
		return isRequried;
	}

	public void setIsRequried(Boolean isRequried) {
		this.isRequried = isRequried;
	}
	
	

}
