package com.ifi.lab.LabDAO.model.Idex;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IdexSite generated by hbm2java
 */
@Entity
@Table(name = "idex_site", catalog = "lab_demo")
public class IdexSite implements java.io.Serializable {

	private int idexSiteId;
	private IdexInstallation idexInstallation;
	private String name;
	private String logo;
	private Integer firstParentId;

	public IdexSite() {
	}

	public IdexSite(int idexSiteId) {
		this.idexSiteId = idexSiteId;
	}

	public IdexSite(int idexSiteId, IdexInstallation idexInstallation,
			String name, String logo, Set<IdexCounter> idexCounters,
			Set<IdexCounter> idexCounters_1) {
		this.idexSiteId = idexSiteId;
		this.idexInstallation = idexInstallation;
		this.name = name;
		this.logo = logo;
	}

	@Id
	@Column(name = "idex_site_id", unique = true, nullable = false)
	public int getIdexSiteId() {
		return this.idexSiteId;
	}

	public void setIdexSiteId(int idexSiteId) {
		this.idexSiteId = idexSiteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idex_installation_id")
	public IdexInstallation getIdexInstallation() {
		return this.idexInstallation;
	}

	public void setIdexInstallation(IdexInstallation idexInstallation) {
		this.idexInstallation = idexInstallation;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "logo")
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}
	
	@Column(name = "first_parent_id")
	public Integer getFirstParentId() {
		return firstParentId;
	}

	public void setFirstParentId(Integer firstParentId) {
		this.firstParentId = firstParentId;
	}

}
